package org.example.View;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.example.Dao.AcervoDAO.BibliotecaDAO;
import org.example.Entities.SistemaDasTelas.BibliotecaSys;
import org.example.Entities.SistemaDasTelas.FuncionarioSys;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;

public class GerenciarAcervo extends JDialog {
    private JPanel MainPanel;
    private JButton btnVerAcervo;
    private JButton btnCadastrarLivro;
    private JButton btnDevolverLivro;
    private JButton btnAlterarLivro;
    private JButton btnRemoverLivro;
    private JButton btnAdicionarConhecimento;
    private JButton btnRemoverAreaConhecimento;
    private JButton btnVoltar;
    private JButton EMPRESTARLIVROButton;
    private final BibliotecaSys bibliotecaSys = new BibliotecaSys();
    private final BibliotecaDAO bibliotecaDAO = new BibliotecaDAO();
    private final FuncionarioSys funcionarioSys = new FuncionarioSys();


    public GerenciarAcervo(JFrame parent) {
        super(parent, "GerenciarAcervo", true);
        this.setContentPane(MainPanel);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);


        btnVerAcervo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verAcervo();
            }
        });
        btnVoltar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                voltar();
            }
        });
        btnCadastrarLivro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cadastrarLivro();
            }
        });
    }

    private void cadastrarLivro() {
        RegisterBookForm registerBookForm = new RegisterBookForm(null);
        registerBookForm.setVisible(true);
    }



    public static void main(String[] args) {
        JFrame frame = new JFrame("GerenciarAcervo");
        frame.setContentPane(new GerenciarAcervo(null).MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void verAcervo() {
        funcionarioSys.listarLivros();
    }

    private void voltar() {
        FuncionarioForm funcionarioForm = new FuncionarioForm(null);
        funcionarioForm.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(7, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Acervo");
        MainPanel.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnVerAcervo = new JButton();
        btnVerAcervo.setText("VER ACERVO");
        MainPanel.add(btnVerAcervo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnVoltar = new JButton();
        btnVoltar.setText("VOLTAR");
        MainPanel.add(btnVoltar, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCadastrarLivro = new JButton();
        btnCadastrarLivro.setText("CADASTRAR LIVRO");
        MainPanel.add(btnCadastrarLivro, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAdicionarConhecimento = new JButton();
        btnAdicionarConhecimento.setText("ADICIONAR AREA DE CONHECIMENTO");
        MainPanel.add(btnAdicionarConhecimento, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRemoverAreaConhecimento = new JButton();
        btnRemoverAreaConhecimento.setText("REMOVER AREA DE CONHECIMENTO");
        MainPanel.add(btnRemoverAreaConhecimento, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDevolverLivro = new JButton();
        btnDevolverLivro.setText("DEVOLVER LIVRO");
        MainPanel.add(btnDevolverLivro, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        EMPRESTARLIVROButton = new JButton();
        EMPRESTARLIVROButton.setText("EMPRESTAR LIVRO");
        MainPanel.add(EMPRESTARLIVROButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAlterarLivro = new JButton();
        btnAlterarLivro.setText("ALTERAR LIVRO");
        MainPanel.add(btnAlterarLivro, new GridConstraints(2, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRemoverLivro = new JButton();
        btnRemoverLivro.setText("REMOVER LIVRO");
        MainPanel.add(btnRemoverLivro, new GridConstraints(2, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
